{
    "openapi":"3.0.2",
    "info": {
        "title":"Garnet API",
        "version":"1.0"
    },
    "tags": [
        {
            "name": "bin",
            "description": "Endpoints to interact with trashcans."
        },
        {
            "name": "district",
            "description": "Endpoints to get demographic information about the area."
        }
    ],
    "servers": [
        {
            "url":"https://localhost:3001/api"
        }
    ],
    "components": {
        "schemas": {
            "hateoas": {
                "type": "object",
                "properties": {
                    "self": {
                        "allOf": [{"$ref": "#/components/schemas/href"}]
                    },
                    "parent": {
                        "allOf": [{"$ref": "#/components/schemas/href"}]
                    }
                }
            },
            "href": {
                "type": "object",
                "properties": {
                    "href": {
                        "type": "string",
                        "format": "url"
                    }
                }
            },
            "district": {
                "type": "object",
                "properties": {
                    "district_number": {
                        "type": "number",
                        "format": "int32"
                    },
                    "district_flag": {
                        "type": "number",
                        "format": "int32"
                    }
                }
            },
            "bin": {
                "type":"object",
                "properties": {
                    "fill_weight": {
                        "type": "number",
                        "format": "float64"
                    },
                    "latitude": {
                        "type": "number",
                        "format": "float64"
                    },
                    "longitude": {
                        "type": "number",
                        "format": "float64"
                    },
                    "trashtype": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "district": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            },
            "error": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "number",
                        "format": "int32"
                    },
                    "error": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "help": {
                        "type": "string",
                        "format": "url"
                    }
                }
            }
        },
        "parameters": {
            "districtId": {
                "name":"districtId",
                "in": "path",
                "required": true,
                "description": "A unique identifier for a single district",
                "schema": {
                    "type": "integer",
                    "format": "int64"
                }
            },
            "binId": {
            "name":"binId",
            "in": "path",
            "required": true,
            "description": "A unique identifier for a single trashcan.",
            "schema": {
                "type": "integer",
                "format": "int64"
                }
            },
            "filled": {
                "name": "filled",
                "in": "query",
                "required": false,
                "description": "Wether only return trashcans that are filled.",
                "example": "true",
                "schema": {
                    "type": "boolean"
                }
            }
        }
    },
    "paths": {
        "/": {
            "get": {
                "description": "Retrieve basic links to navigate the api.",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved information.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                        "properties": {
                                            "_links": {
                                                "type": "object",
                                                "properties": {
                                                    "self":  {
                                                        "allOf": [{"$ref": "#/components/schemas/href"}]
                                                    },
                                                    "bin": {
                                                        "allOf": [{"$ref": "#/components/schemas/href"}]
                                                    },
                                                    "district": {
                                                        "allOf": [{"$ref": "#/components/schemas/href"}]
                                                    }
                                                }
                                            },
                                            "welcome": {
                                                "type": "string"
                                            }
                                        }
                                },
                                "example": {
                                    "_links": {
                                        "self": {
                                            "href": "https://localhost:3001/api/"
                                        },
                                        "bin": {
                                            "href": "https://localhost:3001/api/bin"
                                        },
                                        "district": {
                                            "href": "https://localhost:3001/api/district"
                                        }
                                    },
                                    "welcome": "Welcome to the GarNet REST API. To get more information read the docs at https://localhost:3001"
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "example": {
                                    "status": 405,
                                    "error": "Method not allowed",
                                    "message": "Post method not allowed for this action. Only allowed method(s) are GET.",
                                    "help": "https://localhost:3001/docs"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "example": {
                                    "status": 406,
                                    "error": "Not Acceptable",
                                    "message": "Response is only available as application/json.",
                                    "help": "https://localhost:3001/docs"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "example": {
                                    "status": 415,
                                    "error": "Unsupported Media Type",
                                    "message": "The media format of the requested data is not supported.",
                                    "help": "https://localhost:3001/docs"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/bin": {
            "post": {
                "tags": [
                    "bin"
                ],
                "description":"Create a new trashcan in the system.",
                "parameters": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/bin"
                            },
                            "example": {
                                "fill_weight": 0.0,
                                "latitude": 0.0,
                                "longitude": 0.0,
                                "trashtype": 1,
                                "districts": 2
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Successfully created a new trashcan.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/bin"
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer",
                                                    "format": "int64"
                                                },
                                                "_links": {
                                                    "allOf": [
                                                        {
                                                            "$ref": "#/components/schemas/hateoas" 
                                                        },
                                                        {
                                                            "type": "object",
                                                            "properties": {
                                                                "bin:update": {
                                                                    "allOf": [{"$ref": "#/components/schemas/href" }]
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "id": 2340234,
                                    "fill_weight": 0.0,
                                    "latitude": 0.0,
                                    "longitude": 0.0,
                                    "trashtype": 1,
                                    "district": 2,
                                    "_links": {
                                        "self": {
                                            "href": "http://localhost:3001/v1/bin"
                                        },
                                        "parent": {
                                            "href": "http://localhost:3001/v1"
                                        },
                                        "bin:update": {
                                            "href": "http://localhost:3001/v1/bin/2340234"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "bin"
                ],
                "description": "Retriev all trashcans from the system, optionally only the filled trashcans.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/filled"
                    },
                    {
                        "name": "districts",
                        "in": "query",
                        "description": "The districts within the trashcan should reside.",
                        "required": false,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "format": "int64"
                            }
                        },
                        "example": [1,3,2]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved trashcans",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "allOf": [
                                                    {
                                                        "$ref": "#/components/schemas/bin"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "id": {
                                                                "type": "integer",
                                                                "format": "int64"
                                                            },
                                                            "_links": {
                                                                "allOf": [
                                                                    {
                                                                        "$ref": "#/components/schemas/hateoas"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "bin:update": {
                                                                                "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        "count": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                },
                                "example": {
                                    "data": [
                                        {
                                            "id": 1,
                                            "fill_weight": 0.0,
                                            "latitude": 0.0,
                                            "longitude": 0.0,
                                            "trashtype": 1,
                                            "districts": 2,
                                            "_links": {
                                                "self": {
                                                    "href": "http://localhost:3001/v1/bin"
                                                },
                                                "parent": {
                                                    "href": "http://localhost:3001/v1"
                                                },
                                                "bin:update": {
                                                    "href": "http://localhost:3001/v1/bin/1"
                                                }
                                            }
                                        },
                                        {
                                            "id": 2,
                                            "fill_weight": 0.0,
                                            "latitude": 0.0,
                                            "longitude": 0.0,
                                            "trashtype": 1,
                                            "districts": 2,
                                            "_links": {
                                                "self": {
                                                    "href": "http://localhost:3001/v1/bin"
                                                },
                                                "parent": {
                                                    "href": "http://localhost:3001/v1"
                                                },
                                                "bin:update": {
                                                    "href": "http://localhost:3001/v1/bin/2"
                                                }
                                            }
                                        }
                                    ],
                                    "count": 2
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/bin/{binId}": {
            "patch": {
                "tags": [
                    "bin"
                ],
                "description":"Update a single trashcan",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/binId"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/bin"
                            },
                            "example": {
                                "fill_weight": 0.0
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated the trashcan.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/bin"
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "_links": {
                                                    "$ref": "#/components/schemas/hateoas"
                                                }
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "id": 2,
                                    "fill_weight": 12.5,
                                    "latitude": 0.0,
                                    "longitude": 0.0,
                                    "trashtype": 1,
                                    "districts": 2,
                                    "_links": {
                                        "self": {
                                            "href": "http://localhost:3001/v1/bin/2"
                                        },
                                        "parent": {
                                            "href": "http://localhost:3001/v1/bin"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/district": {
            "post": {
                "tags": [
                    "district"
                ],
                "description":"Create a new district",
                "parameters": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/district"
                            },
                            "example": {
                                "district_number": 41,
                                "district_flag": 22
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Successfully created a new district.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "number",
                                                    "format": "int32"
                                                }
                                            }
                                        },
                                        {
                                            "$ref": "#/components/schemas/district"
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "_links": {
                                                   "allOf": [
                                                        {
                                                            "$ref": "#/components/schemas/hateoas"
                                                        },
                                                        {
                                                            "type": "object",
                                                            "properties": {
                                                                "district:update": {
                                                                    "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                },
                                                                "district:bin": {
                                                                    "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                }
                                                            }
                                                        }
                                                   ]
                                                }
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "id": 12,
                                    "district_number": 12,
                                    "district_flag": "Petershausen",
                                    "_links": {
                                        "self": {
                                            "href": "http://localhost:3001/api/district"
                                        },
                                        "parent": {
                                            "href": "http://localhost:3001/api"
                                        },
                                        "district:update": {
                                            "href": "http://localhost:3001/api/district/12"
                                        },
                                        "district:bin": {
                                            "href": "http://localhost:3001/api/district/12/bin"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            },

            "get": {
                "tags": [
                    "district"
                ],
                "description": "Retriev all districts",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/filled"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved available districts.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "allOf": [
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "id": {
                                                                "type": "number",
                                                                "format": "int32"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "$ref": "#/components/schemas/district"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "_links": {
                                                                "allOf": [
                                                                    {
                                                                        "$ref": "#/components/schemas/hateoas"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "district:update": {
                                                                                "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                            },
                                                                            "district:bin": {
                                                                                "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        "count": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                },
                                "example": {
                                    "data": [
                                        {
                                            "id": 1,
                                            "district_number": 12,
                                            "district_flag": "Petershausen",
                                            "_links": {
                                                "self": {
                                                    "href": "http://localhost:3001/v1/district"
                                                },
                                                "parent": {
                                                    "href": "http://localhost:3001/v1"
                                                },
                                                "district:update": {
                                                    "href": "http://localhost:3001/v1/district/1"
                                                },
                                                "district:bin": {
                                                    "href": "http://localhost:3001/v1/district/1/bin"
                                                }
                                            }
                                        },
                                        {
                                            "id": 2,
                                            "district_number": 13,
                                            "district_flag": "Paradies",
                                            "_links": {
                                                "self": {
                                                    "href": "http://localhost:3001/v1/district"
                                                },
                                                "parent": {
                                                    "href": "http://localhost:3001/v1"
                                                },
                                                "district:update": {
                                                    "href": "http://localhost:3001/v1/district/2"
                                                },
                                                "district:bin": {
                                                    "href": "http://localhost:3001/v1/district/2/bin"
                                                }
                                            }
                                        }
                                    ],
                                    "count": 2
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/district/{districtId}": {
            "patch": {
                "tags": [
                    "district"
                ],
                "description": "Update a specific district.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/districtId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update the district.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "number",
                                                    "format": "int32"
                                                }
                                            }
                                        },
                                        {
                                            "$ref": "#/components/schemas/district"
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "_links": {
                                                    "allOf": [
                                                        {
                                                            "$ref": "#/components/schemas/hateoas"
                                                        },
                                                        {
                                                            "type": "object",
                                                            "properties": {
                                                                "district:bin": {
                                                                    "allOf": [{"$ref": "#/components/schemas/href"}]
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "id": 12,
                                    "district_number": 12,
                                    "district_flag": "Petershausen",
                                    "_links": {
                                        "self": {
                                            "href": "http://localhost:3001/v1/district/12"
                                        },
                                        "parent": {
                                            "href": "http://localhost:3001/v1/district"
                                        },
                                        "district:bin": {
                                            "href": "http://localhost:3001/v1/district/12/bin"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/district/{districtId}/bin": {
            "get": {
                "tags": [
                    "district"
                ],
                "description": "Get all trashcans of within a specific district",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/districtId"
                    },
                    {
                       "$ref": "#/components/parameters/filled"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved values.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "allOf": [
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "id": {
                                                                "type": "string",
                                                                "format": "int32"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "$ref": "#/components/schemas/bin"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "_links": {
                                                                "allOf": [
                                                                    {
                                                                        "$ref": "#/components/schemas/hateoas"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "bin:update": {
                                                                                "type": "string",
                                                                                "format": "url"
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        "count": {
                                            "type": "number",
                                            "format": "int64"
                                        }
                                    }
                                },
                                "example": {
                                    "data": [
                                        {
                                            "id": 1,
                                            "fill_weight": 12,
                                            "latitude": 2.44,
                                            "longitude": 1.43,
                                            "trashtype": 4,
                                            "districts": 5,
                                            "_links": {
                                                "self":  "http://localhost:3001/v1/district/12/bin",
                                                "parent": "http://localhost:3001/v1/district/12",
                                                "bin:update": "http://localhost:3001/v1/bin/1"
                                            }
                                        },
                                        {
                                            "id": 2,
                                            "fill_weight": 12,
                                            "latitude": 2.45,
                                            "longitude": 1.45,
                                            "trashtype": 4,
                                            "districts": 5,
                                            "_links": {
                                                "self":  "http://localhost:3001/v1/district/12/bin",
                                                "parent": "http://localhost:3001/v1/district/12",
                                                "bin:update": "http://localhost:3001/v1/bin/2"
                                            }
                                        }
                                    ],
                                    "count": 2
                                }  
                            }
                        }
                    },
                    "405": {
                        "description": "Used HTTP method is not allowed.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "406": {
                        "description": "Ressource is not available in the required form.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Wrong media type used for the request.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}